### PR TITLE
Api update

### PR DESCRIPTION
**Pull request by bahjaat**
Mogelijk toegevoegd voor het later zetten van de api-key

### CODE REVIEW

**Comment by joshuadegier** [comment]
I guess you could set the key straight when adding the class to the container. But perhaps there are use cases where multiple keys are used. Since it's not a breaking change I've merged the PR. Thanks.

**Comment by bahjaat** [comment]
Thanks. Yes, I'm using it for multiple sports clubs.

**Comment by bahjaat** [comment]
Maybe give it a new tag?

**Comment by joshuadegier** [comment]
Done @ https://github.com/PendoNL/php-club-dataservice/releases/tag/0.2

**Pull request merged**
